In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [6]:
pd.__version__

'2.2.2'

In [139]:
#read csv and make a panda dataframe with columns header
df = pd.read_csv("laptops.csv")
type(df)

pandas.core.frame.DataFrame

In [140]:
df.size

25920

In [141]:
#number of rows
len(df.index), df.index,df.shape[0]

(2160, RangeIndex(start=0, stop=2160, step=1), 2160)

In [142]:
#number of brands
df.Brand.nunique(), df['Brand'].nunique()

(27, 27)

In [143]:
#count missing values
df.isnull().sum().sum(), df.Brand.isnull().sum(), len(df[df['Brand'] == np.nan])

(1417, 0, 0)

In [144]:
#maximum 'final price'
#df['Final Price'] = 'Final_Price'
df.columns = df.columns.str.lower().str.replace(' ', '_')
df[df.brand == 'Dell'].final_price.max()

3936.0

In [145]:
df.screen.median()

15.6

In [146]:
#median of screen - is the 50th of describe
df.screen.describe()

count    2156.000000
mean       15.168112
std         1.203329
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: screen, dtype: float64

In [147]:
#get the most frequent value for screen aka MODE
df.screen.mode()

0    15.6
Name: screen, dtype: float64

In [148]:
#fill NaN with mode and call describe to check median
df.screen.fillna(df.screen.mode())
df.screen.describe()

count    2156.000000
mean       15.168112
std         1.203329
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: screen, dtype: float64

In [149]:
df.screen.median()

15.6

In [234]:
df_brand = df[df.brand == 'Innjoo']
df_brand

laptop status   brand model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                cpu  ram  storage storage_type  gpu  screen touch  final_price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [235]:
df_brand_columns = df_brand[['ram','storage','screen']]
df_brand_columns

ram  storage  screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [236]:
x = np.array(df_brand_columns)
type(x), x

(numpy.ndarray,
 array([[  8. , 256. ,  15.6],
        [  8. , 512. ,  15.6],
        [  4. ,  64. ,  14.1],
        [  6. ,  64. ,  14.1],
        [  6. , 128. ,  14.1],
        [  6. , 128. ,  14.1]]))

In [237]:
xT = x.T
xT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [238]:
x.shape, xT.shape

((6, 3), (3, 6))

In [239]:
xTx = np.matmul(xT,x)
xTx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [240]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [241]:
xTx_i = np.linalg.inv(xTx)
xTx_i

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [242]:
i_xT = xTx_i.dot(xT)
i_xT

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [243]:
w = i_xT.dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [244]:
w_sum = w.sum()
w_sum

91.29988062995815